---
label: product
hide_body: true
fields:
- name: id
  type: text
  config:
    required: false
  label: ID
- name: name
  type: text
  config:
    required: false
  label: Name
- name: price
  type: number
  label: Price
  description: ''
  default: 0
  required: true
  config:
    min: 
    max: 
    step: 
- name: description
  type: text
  config:
    required: false
  label: description
- name: image
  type: file
  config:
    maxSize: 64
  label: Image
- name: product-url
  type: text
  config:
    required: false
  label: product-url
